feat: add responsive adjustments on account screen
FuelLabs/fuel-explorer pull request #103
Opened 2023-11-08 21:59 UTC by pedronauck

⭐ Closes [FE-4](https://linear.app/fuel-network/issue/FE-4/account-page-mobile-ui)

2023-11-09 00:42 UTC, LuizAsFight requested changes
not enough space to show balance value

![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/4d9b368e-8306-48a2-8d35-f3d17e5b1503)

2023-11-09 01:02 UTC, LuizAsFight requested changes

2023-11-09 01:02 UTC, LuizAsFight commented on packages/ui/src/hooks/useBreakpoints.ts
> +  const isTablet = useMedia('(min-width: 577px)');
value here is wrong right? tablet.is `640px`

2023-11-09 02:03 UTC, LuizAsFight requested changes
tabs should be horizontal also when in mobile. 

 like in the mockups

<img width="381" alt="image" src="https://github.com/FuelLabs/fuel-explorer/assets/8636507/8b81e9ff-b29a-4f87-8ff0-149f5eb27abd">

2023-11-10 03:38 UTC, pedronauck commented
> tabs should be horizontal also when in mobile.
> 
> like in the mockups
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/8636507/281592465-8b81e9ff-b29a-4f87-8ff0-149f5eb27abd.png">

@LuizAsFight  ✅

2023-11-10 03:39 UTC, pedronauck commented on packages/ui/src/hooks/useBreakpoints.ts
> +  const isTablet = useMedia('(min-width: 577px)');
I tried to use the same value, the only way it's able is being using javascript variables, by using css vars wasn't possible

2023-11-10 03:39 UTC, pedronauck commented
> not enough space to show balance value
> 
> ![image](https://user-images.githubusercontent.com/8636507/281580638-4d9b368e-8306-48a2-8d35-f3d17e5b1503.png)

@LuizAsFight I don't know about why you were talking here, but I guess it was fixed by some merge

2023-11-10 19:50 UTC, LuizAsFight requested changes
<img width="811" alt="image" src="https://github.com/FuelLabs/fuel-explorer/assets/8636507/470949ee-5c69-45ae-bf73-cf9500de0f58">

you don't need this padding in the internal content, padding is handled by rootlayout now

2023-11-10 19:54 UTC, LuizAsFight requested changes

2023-11-10 19:54 UTC, LuizAsFight commented on packages/app/src/app/account/[id]/transactions/page.tsx
> +      className="mobile:p-0 tablet:p-0 desktop:p-0"
`mobile` is not needed , we can use as default one

this applies also for other usages of `mobile:` in this PR

```suggestion
      className="p-0 tablet:p-0 desktop:p-0"
```

2023-11-10 19:54 UTC, LuizAsFight commented on packages/ui/src/theme/tailwind-preset.ts
> +        mobile: `${breakpoints.mobile}px`,
mobile is not needed

2023-11-10 22:10 UTC, LuizAsFight approved these changes

2023-11-10 22:10 UTC, merged