refactor: remove type change on click
FuelLabs/fuel-explorer pull request #107
Opened 2023-11-10 19:41 UTC by matt-user

closes FE-27

2023-11-10 20:30 UTC, luizstacio approved these changes

2023-11-10 20:31 UTC, luizstacio requested changes
We should add to this links a hover with color primary

2023-11-13 17:10 UTC, luizstacio commented
Can you also add the hover on the block?
<img width="401" alt="Screenshot 2023-11-13 at 2 09 56 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/f9c19c15-695f-4376-aec3-8bf4256c6f8e">

2023-11-13 17:11 UTC, luizstacio commented
- When we are rendering a asset_id we don't need to have a link;
<img width="396" alt="Screenshot 2023-11-13 at 2 10 25 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/ed0b7b6a-ce97-4164-94b9-0ab32bec9999">

2023-11-15 14:47 UTC, luizstacio commented
> Can you also add the hover on the block? <img alt="Screenshot 2023-11-13 at 2 09 56 PM" width="401" src="https://user-images.githubusercontent.com/3941923/282535292-f9c19c15-695f-4376-aec3-8bf4256c6f8e.png">

Can you do this also?

2023-11-15 18:58 UTC, LuizAsFight requested changes
can we make the address always link style, instead of only when hovering?

on this way the user knows it's a link, otherwise user needs to hover to know it's a link

2023-11-15 19:01 UTC, LuizAsFight requested changes
![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/e00c29f0-79de-418a-bf73-e010b9f63156)

add pointer to copy button

2023-11-15 19:02 UTC, LuizAsFight requested changes
- add link style also when not hovering
- remove useless icon

![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/69354037-f917-45f1-a814-f8243c9fb742)

2023-11-15 19:04 UTC, LuizAsFight requested changes
before:
![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/d6858e51-00a7-4b07-8a82-4a888cb88a2d)

----
after
![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/75e0783e-d132-45ec-8656-78bf01d0526e)

---
address size is looking way smaller than before, and also disaligned

2023-11-15 21:39 UTC, LuizAsFight requested changes
![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/eddff4ea-179a-4560-810d-5900fa788f09)

not showing sender / recipient anymore

2023-11-15 23:13 UTC, luizstacio requested changes
The size and font weight should be the same of previous versions. It looks a bit bigger and bold now.
<img width="228" alt="Screenshot 2023-11-15 at 8 12 32 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/53d45b27-f2bd-4273-bbde-fadc8767abb3">
<img width="139" alt="Screenshot 2023-11-15 at 8 12 19 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/61f0415d-06fb-4bce-a66b-b9c5e1095c21">

2023-11-16 23:28 UTC, luizstacio submitted a review, later dismissed

2023-11-17 03:34 UTC, LuizAsFight submitted a review, later dismissed

2023-11-17 03:34 UTC, LuizAsFight commented on packages/ui/src/components/Copyable/Copyable.tsx
> +            className="cursor-pointer"
this fix would be better on UI side ?

`<IconButton>` is a Button I'd expect it to be pointer by default, unless it's disabled/readOnly

2023-11-17 03:34 UTC, LuizAsFight commented on packages/ui/src/components/Copyable/Copyable.tsx
> +            className="cursor-pointer"
this would also fix all other IconButtons

<img width="341" alt="image" src="https://github.com/FuelLabs/fuel-explorer/assets/8636507/32a7055e-84fa-4a22-9283-feae0e29c6bb">

2023-11-20 23:21 UTC, luizstacio approved these changes

2023-11-20 23:41 UTC, merged