feat: improve search UI
FuelLabs/fuel-explorer pull request #119
Opened 2023-11-15 22:34 UTC by matt-user

closes FE-13

2023-11-21 01:17 UTC, luizstacio requested changes
<img width="300" alt="Screenshot 2023-11-20 at 10 09 41 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/7852b14e-e177-409d-8791-0f6df30744a3">

1. ~~You can remove the placeholder.~~
2. ~~The helper text could be smaller and need to have a bit more spacing on the top of it.~~

<img width="300" alt="Screenshot 2023-11-20 at 10 10 54 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/8654222f-fcec-4a33-bf86-b6e134823910">

4. The error should be shown in the place of the helper text with red letter's.

<img width="300" alt="Screenshot 2023-11-20 at 10 12 34 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/afa589c0-5d0b-41eb-83eb-3c40f24350d4">

6. ~~The dropdown should have the same width of the input.~~
7. ~~The search should be trigger with enter also.~~

<img width="300" alt="Screenshot 2023-11-20 at 10 13 56 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/baee9619-8acd-4c09-beac-0e340589352e">

9. ~~The Focus when using keyboard should have the same background color.~~
10. When loading the actions should become a spinner and the dropdown should be closed, right now, it opens with previous data and them change with the new data.

2023-11-27 21:52 UTC, pedronauck requested changes

2023-11-27 21:52 UTC, pedronauck commented on packages/app/src/app/transactions/page.tsx
> +  const searchResult = await search({ query: searchQuery });
Hm, I'm pretty sure this is not the best way to handle this. In fact, you don't need to fetch in the server component, since this is a mutation that just happens after some interaction...

The best approach for this is:
- Create a server action using the `'use server'` that will handle the fetch logic
- Use `useAct`, or `form`, or `startTransaction` to trigger after click on submit

So, by doing this you will avoid all this prop dilling and workaround back-and-fourth of data in the components tree in order to retrieve the data.

2023-11-28 18:21 UTC, pedronauck requested changes
![CleanShot 2023-11-28 at 15 19 56@2x](https://github.com/FuelLabs/fuel-explorer/assets/2029172/7a792ee6-d49d-4c31-9085-528594f07287)

- Need to adjust the dropdown to work in less resolutions
- When clicking on submit it's adding the loading in both buttons `clear` and `submit`, should be just in the `submit`

2023-11-28 20:47 UTC, pedronauck approved these changes

2023-11-28 21:04 UTC, luizstacio requested changes
- On Enter it should trigger the search.
- The error should not be highlight with hover, and letters should be red.

2023-11-28 22:00 UTC, luizstacio approved these changes

2023-11-28 22:00 UTC, merged