chore: improve inputs and outputs
FuelLabs/fuel-explorer pull request #125
Opened 2023-11-21 19:33 UTC by pedronauck

⭐ Closes FE-18
⭐ Closes FE-19
⭐ Closes FE-53

2023-11-22 02:31 UTC, LuizAsFight approved these changes

2023-11-22 12:59 UTC, luizstacio requested changes
Why we added a final balance? https://fuel-explorer-6r3xlxjaj-fuel-labs.vercel.app/tx/0xb2c1a99f26f880b2fc2327b0241eca525ca549419a2f8da6d7c02df64d5e4ef1

2023-11-22 17:44 UTC, LuizAsFight requested changes
spent shows whole value but output only shows 3 decimals, is this correct ?

![image](https://github.com/FuelLabs/fuel-explorer/assets/8636507/0dff0818-9794-43ee-92e2-0cfeb036f08f)

2023-11-28 01:57 UTC, luizstacio requested changes
Ex.: https://fuel-explorer-o7yc4415r-fuel-labs.vercel.app/tx/0x520ae720502fe974528bf231f152a7edc9d7b667d501e6d3d06346f18fa5a2c9
-  The outputs show "This is the UTXO spent in the transaction". What is not true it created a new UTXO for the destination account. I think is nice to have the helper but we should remove the word UTXO and replace with amount. "This is the Amount sent in the transaction".

2023-11-28 22:03 UTC, luizstacio approved these changes

2023-11-29 18:20 UTC, LuizAsFight approved these changes

2023-11-29 18:20 UTC, merged