chore: update beta-5
FuelLabs/fuel-explorer pull request #139
Opened 2023-12-08 20:54 UTC by pedronauck

2024-01-10 15:58 UTC, luizstacio requested changes

2024-01-10 15:58 UTC, luizstacio commented on deployment/Dockerfile
> +ENV FUEL_PROVIDER_BETA5="${FUEL_PROVIDER_BETA5}"
Why we change the name of the provider here?

2024-01-10 16:00 UTC, luizstacio commented on packages/app/src/systems/Transaction/component/TxScreen/TxScreenSimple.tsx
> -              }
Gas limit is available for transaction of type Script, you can find it on the policies array.

2024-01-11 04:46 UTC, LuizAsFight commented on deployment/Dockerfile
> +ENV FUEL_PROVIDER_BETA5="${FUEL_PROVIDER_BETA5}"
`FUEL_PROVIDER_URL` was better IMO to avoid needing to change later.

2024-01-11 04:57 UTC, LuizAsFight requested changes
in transaction screen, can we hide the fee block when it's a mint transaction?

2024-01-11 17:52 UTC, merged