feat: structure changes to portal + migrate bridge tx list
FuelLabs/fuel-explorer pull request #159
Opened 2024-02-06 16:00 UTC by LuizAsFight

- Adapt struct to run the `@fuels/ui` inside of `app-portal` package
- BridgeTxList: purge `@fuel-ui` and replace with `@fuels/ui`

Missing on this PR: some colors are still not coming from theme, we need to fix it in next PRs

2024-02-06 16:26 UTC, luizstacio requested changes

2024-02-06 16:26 UTC, luizstacio commented on packages/ui/src/components/Theme/useTheme.tsx
>    }
The fuel/ui do not have a mechanism for this?

2024-02-07 00:51 UTC, LuizAsFight commented on packages/ui/src/components/Theme/useTheme.tsx
>    }
this is inside `@fuels/ui` already

2024-02-07 00:58 UTC, luizstacio approved these changes

2024-02-07 01:28 UTC, merged