chore: explorer feedback consistency
FuelLabs/fuel-explorer pull request #179
Opened 2024-02-20 20:42 UTC by helciofranco

- Updates icons (sync with the new website)
- Updates link structure
- Adjust typography
- Adjust spacing 
- Match new layout (almost)

| 📷 Demo |
|--------|
| <img width="1560" alt="Screenshot 2024-02-20 at 16 41 50" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/f32a5236-e147-4954-9db4-a593ce4564ac"> |

2024-02-20 21:25 UTC, luizstacio approved these changes

2024-02-20 21:25 UTC, luizstacio requested changes
We should change the a to use Link from the UI lib?

2024-02-21 02:57 UTC, pedronauck commented
> We should change the a to use Link from the UI lib? @pedronauck

Would be better to use it, of course

2024-02-21 12:01 UTC, luizstacio requested changes

2024-02-21 12:01 UTC, luizstacio commented on packages/app-explorer/src/systems/Core/components/Footer/Footer.tsx
> +            <a
Can you change to use the Link from the ui library

2024-02-21 12:52 UTC, helciofranco commented on packages/app-explorer/src/systems/Core/components/Footer/Footer.tsx
> +            <a
https://github.com/FuelLabs/fuel-explorer/pull/179/commits/45123d9ceeb05f7879bfca2f043497e7735d1d7a

2024-02-21 15:41 UTC, luizstacio approved these changes

2024-02-21 15:41 UTC, merged