fix: nextjs error logs
FuelLabs/fuel-explorer pull request #202
Opened 2024-02-27 22:12 UTC by helciofranco

This PR fixes how `Next.JS` resolves `app-portal` imports.

| No more errors |
|----------|
| <img width="609" alt="clean logs" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/9b5da62b-d0e1-401a-b9a1-f3c91a6148b4"> |

2024-02-27 22:14 UTC, helciofranco commented on packages/app-explorer/package.json
> +    "@tanstack/react-query": "4.36.1",
This downgrade is intentional.

I did it just to keep only one version of `react-query` in our final bundle.
Mostly because everywhere was on `v4` and we're not using any `v5 feature` currently.

<img width="567" alt="downgrade" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/0b312cf5-2442-4902-95b4-749fc81bee66">

We might upgrade it in a follow-up PR.

2024-02-27 22:52 UTC, pedronauck requested changes

2024-02-27 22:52 UTC, pedronauck commented on packages/app-explorer/src/app/bridge/history/page.tsx
> +'use client';
this page shouldn't have `use client` here

2024-02-27 22:52 UTC, pedronauck commented on packages/app-explorer/src/app/bridge/page.tsx
> +'use client';
this page shouldn't have `use client` here

2024-02-27 22:57 UTC, helciofranco commented on packages/app-explorer/src/app/bridge/history/page.tsx
> +'use client';
do you remember the reason? 
there are a few hooks in this page blocking the build due to the server components.

2024-02-27 22:58 UTC, helciofranco commented on packages/app-explorer/src/app/bridge/history/page.tsx
> +'use client';
```
app-explorer:build: ../app-portal/src/systems/Assets/containers/AssetsDialog.tsx
app-explorer:build: Error: 
app-explorer:build:   × You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
```

2024-02-28 13:57 UTC, helciofranco commented on packages/app-explorer/src/app/bridge/page.tsx
> +'use client';
https://github.com/FuelLabs/fuel-explorer/pull/202/commits/68500623b8aba8f718e7a2105f60a834b26a7b1b

2024-02-28 17:42 UTC, pedronauck approved these changes

2024-02-28 17:42 UTC, merged