feat: add e2e tests
FuelLabs/fuel-explorer pull request #219
Opened 2024-03-08 05:23 UTC by LuizAsFight

2024-03-19 00:25 UTC, luizstacio approved these changes

2024-03-19 00:40 UTC, luizstacio requested changes

2024-03-19 00:40 UTC, luizstacio commented on packages/app-portal/src/systems/Assets/services/asset.tsx
> +    const erc20MintHash = await (erc20 as any).write.mint(
Why we need this as any here?

2024-03-19 00:40 UTC, luizstacio commented on packages/app-portal/src/systems/Bridge/hooks/useBridge.tsx
> +          ethPublicClient: ethPublicClient as any,
Why we need this as any?

2024-03-19 06:26 UTC, LuizAsFight commented on packages/app-portal/src/systems/Bridge/hooks/useBridge.tsx
> +          ethPublicClient: ethPublicClient as any,
contracts typing stopped to work after upgrading the eth libraries (wagmi, viem). it will be fixed on next prs

2024-03-19 06:27 UTC, LuizAsFight commented on packages/app-portal/src/systems/Bridge/hooks/useBridge.tsx
> +          ethPublicClient: ethPublicClient as any,
I updated the PR description including it

2024-03-19 10:35 UTC, HoTandy approved these changes
I've reviewed the associated issue https://github.com/FuelLabs/fuel-explorer/issues/239 through the PR link and now the bridge is connecting to the dev wallet.

2024-03-19 14:30 UTC, helciofranco reviewed
LGTM, just left some questions regarding the package versions

2024-03-19 14:30 UTC, helciofranco commented on packages/e2e-tests/package.json
> +    "@synthetixio/synpress": "https://github.com/LuizAsFight/synpress",
should we move it to this monorepo?

2024-03-19 14:30 UTC, helciofranco commented on packages/app-explorer/package.json
>      "@fuel-wallet/sdk": "0.15.2",
can we take the opportunity to remove `@fuel-wallet/sdk`?
not used anymore

2024-03-19 14:30 UTC, helciofranco commented on packages/app-portal/package.json
>      "@fuel-wallet/sdk": "0.15.2",
can we take the opportunity to remove `@fuel-wallet/sdk`?
not used anymore

2024-03-19 14:30 UTC, helciofranco commented on packages/app-portal/src/providers.tsx
> +  const [queryClient] = useState(() => new QueryClient());
Commenting just in case you think it's still necessary as `react-query` config.

Previously it had `retry false` etc (when it was on `@fuel-wallet/react` provider).

2024-03-19 14:30 UTC, helciofranco commented on packages/graphql/package.json
> +    "@fuels/ts-config": "dev",
do we need to release something before merging this PR?

2024-03-19 14:30 UTC, helciofranco commented on packages/ui/package.json
> +    "@fuels/assets": "dev",
do we need to release something before merging this PR?

2024-03-19 14:31 UTC, helciofranco commented on packages/app-portal/src/providers.tsx
> +  const [queryClient] = useState(() => new QueryClient());
https://github.com/FuelLabs/fuels-wallet/blob/c5b986ff08955b5b7d47f61404686399f0eecd86/packages/react/src/providers/FuelHooksProvider.tsx#L12-L15

<img width="385" alt="Screenshot 2024-03-19 at 10 31 48" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/aa71ff57-b53d-4a4b-87e5-5430e46ed02d">

2024-03-19 22:46 UTC, LuizAsFight commented on packages/e2e-tests/package.json
> +    "@synthetixio/synpress": "https://github.com/LuizAsFight/synpress",
this is temporary I will open a PR against the origin repo when the work is finished. if they don't accept then yes we can think on moving it to a better place. I will create an issue for us to check this in the future

2024-03-19 23:10 UTC, LuizAsFight commented on packages/app-portal/src/providers.tsx
> +  const [queryClient] = useState(() => new QueryClient());
I think due to changes we did in structure/connectors etc we will not need this anymore. if it becomes a problem again in development we can add again. not seeing the need RN. nice catch

2024-03-21 18:12 UTC, helciofranco approved these changes

2024-03-21 19:21 UTC, luizstacio approved these changes

2024-03-21 19:21 UTC, merged