chore: copy over explorer v0.18.4
FuelLabs/fuel-explorer pull request #25
Opened 2023-07-20 14:19 UTC by ra0x3

### Description
- Copies over the block explorer from the indexer repo v0.18.4
- We will continue to migrate changes over, as we change the explorer
- However, there has to probably be a better way than copying files over?
  - Copying isn't terrible, it's just you have to make a few changes to the files after you copy them over (since the original files come from a different workspace) 

### Testing steps
- [ ] cd `fuel-explorer/packages/fuel-explorer`
- [ ] `forc index build` (using `forc index v0.18.4`)

2023-07-23 17:02 UTC, Braqzen reviewed
In the README I'm stuck on spinning up the container. I've left it running for a while and it's stuck on attaching `Attaching to fuel-explorer-fuel-indexer-1, fuel-explorer-postgres-1`.

Deploying the indexer also fails as it doesn't find some directory.

@luizstacio may be able to explain the remote merge to keep history rather than copy / pasting

2023-07-31 13:58 UTC, ra0x3 commented on packages/fuel-explorer/fuel-explorer/src/lib.rs
> +        let _transactions = block_data
@Braqzen correct

2023-07-31 14:02 UTC, ra0x3 commented on packages/fuel-explorer/fuel-explorer/src/lib.rs
> +        let _block_frag = BlockIdFragment::from(block_data.header.id);
[See comment](https://github.com/FuelLabs/fuel-explorer/pull/25#discussion_r1279339516)

2023-07-31 14:05 UTC, Braqzen commented on packages/fuel-explorer/fuel-explorer/src/lib.rs
> +// TODO: We use a lot of manual type conversion below due to https://github.com/FuelLabs/fuel-indexer/issues/286
It is a preference for UX and I didn't say that it wasn't straightforward. 
My point of having to scroll to find what you're looking for has not been countered but okay.

2023-07-31 14:07 UTC, Braqzen approved these changes
utACK for the deployment

2023-07-31 14:11 UTC, luizstacio requested changes
We need to keep the basic infra, I saw on this PR we added a new docker-compose, and removed basic infra package.json and scripts.

The current docker on the root folder already handles spinning a fuel-core with data inside.

Do you think we should change this? Why?

2023-07-31 14:26 UTC, ra0x3 commented
@luizstacio Doh! Didn't intend to remove anything, but looks like some files were left off when I renamed the package. I'll add those back 👌🏽

2023-07-31 15:22 UTC, closed without merging