feat: add L1 indexer to fetch contract logs for the bridge
FuelLabs/fuel-explorer pull request #291
Opened 2024-04-04 22:11 UTC by helciofranco

Add L1 indexer, it'll sync contract events logs from a given start block number.
After that, it'll keep watching the blockchain for new logs and blocks.

New env vars have been added to the graphql:
- `FUEL_CHAIN_NAME` (example `fuelBeta5`)
- `ETH_CHAIN_NAME` (example `sepolia`)
- `ETH_ALCHEMY_ID` (your alchemy key)
- `ETH_INFURA_ID` (your infura key – used as fallback to alchemy)

###  📷  Indexer demo
| `pnpm sync:bridge` |
| --- |
| <video src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/8780375a-b352-48b4-9975-bc1f6093b9ab" /> |

### 💾  API demo
| Query | Result |
| --- | --- |
| <img width="809" alt="Screenshot 2024-04-04 at 18 01 16" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/26fb18b1-4f66-419f-9bc6-42958073f5df"> | <img width="652" alt="Screenshot 2024-04-04 at 18 01 27" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/1b36f91f-70b7-4194-b131-0994cd3a5518"> |

2024-04-10 20:39 UTC, luizstacio requested changes

2024-04-10 20:39 UTC, luizstacio commented on .github/workflows/docker-publish.yml
> +          context: .
We should not change the root dir here; this makes the image publish all the code from the repo instead of only the graphql package, drastically increasing the image size.

2024-04-11 00:06 UTC, luizstacio commented on packages/graphql-new/src/application/uc/WatchBridgeContractLogs.ts
> +    }
How watchLogs work? If the socket is closed as example by the server it autoReconnects?

2024-04-11 13:02 UTC, helciofranco commented on .github/workflows/docker-publish.yml
> +          context: .
@luizstacio indeed :( 

I'll need to figure out how to get rid of this – let me find a time to check that today.

I've added this because `graphql-new` package has a peer dependency on the `@fuel-explorer/contract-ids`.
(Outside that `context`)

Does that make sense?

2024-12-10 09:03 UTC, helciofranco commented
Closing this as it has become too outdated. 
We can reopen it later if still relevant.

2024-12-10 09:03 UTC, closed without merging