Fixed Issue #251 - Bridge docs link opening in the same tab
FuelLabs/fuel-explorer pull request #305
Opened 2024-04-20 09:17 UTC by Manav2808

2024-04-20 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/fuel-explorer?pullRequest=305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/fuel-explorer?pullRequest=305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/fuel-explorer?pullRequest=305) it.</sub>

2024-04-26 12:54 UTC, helciofranco requested changes
Hey there! 

Thanks for you contribution, left just a small comment.

2024-04-26 12:54 UTC, helciofranco commented on packages/app-portal/src/systems/Bridge/pages/Bridge.tsx
> +          <a
We just need change to keep using that `Link`.
It adds a pretty icon and other styles to it.

You can keep `target` and `rel` as you did. That looks good.

```suggestion
          <Link
```

2024-04-26 13:50 UTC, Manav2808 commented on packages/app-portal/src/systems/Bridge/pages/Bridge.tsx
> +          <a
Done.

2024-04-26 14:06 UTC, helciofranco requested changes

2024-04-26 14:06 UTC, helciofranco commented on packages/app-portal/src/systems/Bridge/pages/Bridge.tsx
> +            target="_blank"
You missed the `isExternal` prop (that property is adding an icon there)

```suggestion
            isExternal
            target="_blank"
```

2024-04-26 14:13 UTC, Manav2808 commented on packages/app-portal/src/systems/Bridge/pages/Bridge.tsx
> +            target="_blank"
Oh, my bad. Now Done.

2024-04-26 14:29 UTC, merged