fix: casting of contracts and transactions as any
FuelLabs/fuel-explorer pull request #316
Opened 2024-04-25 20:15 UTC by arthurgeron

Replaced `any` castings by the correct usages, focusing on contracts and transactions.

2024-05-27 18:07 UTC, helciofranco approved these changes

2024-05-27 22:00 UTC, pedronauck requested changes

2024-05-27 22:00 UTC, pedronauck commented on packages/app-explorer/src/systems/Transaction/component/TxScripts/TxScripts.tsx
> +    if (typeof value === 'object') return { ...acc, [key]: parseJson(value) };
```suggestion
    if (typeof value === 'object') {
      return { ...acc, [key]: parseJson(value) }
    }
```

2024-05-29 20:20 UTC, arthurgeron commented on packages/app-explorer/src/systems/Transaction/component/TxScreen/TxScreenLoader.tsx
> +  return <TxScreenSimple isLoading transaction={undefined} />;
I've changed the typing for TxScreenSimple so we can conditionally permit for a transaction object to not be passed.

2024-05-29 20:22 UTC, arthurgeron commented on packages/app-explorer/src/systems/Transaction/component/TxScripts/TxScripts.tsx
> +    if (typeof value === 'object') return { ...acc, [key]: parseJson(value) };
Good catch! Fixed

2024-06-04 16:35 UTC, pedronauck approved these changes

2024-06-04 19:54 UTC, merged