feat: sort ecosystem projects by "live" flag
FuelLabs/fuel-explorer pull request #318
Opened 2024-04-26 18:22 UTC by helciofranco

- Projects marked as `live` are sorted first in the projects list.
- Then, a secondary alphabetical sorting is applied.

| Example |
| --- |
| <img width="1186" alt="Screenshot 2024-04-26 at 14 22 36" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/2307dbf9-fa9a-478c-92dc-a6f0ac9dc6b6"> |

2024-04-29 14:00 UTC, arthurgeron commented on packages/app-portal/src/systems/Ecosystem/hooks/useEcosystem.tsx
> +    return projects.sort(sortProjects);
This might be a way to centralize the logic into a single flow,  but it's not necessarily a better approach, just a suggestion
```JS
    const { projects = [], search, filter } = state.context;

    let processedProjects = projects;

    if (search || filter) {
      processedProjects = processedProjects.reduce((acc, project) => {
        const matchesSearch = search ? project.name.toLowerCase().includes(search.toLowerCase()) : true;
        const matchesFilter = filter ? project.tags.includes(filter) : true;

        if (matchesSearch && matchesFilter) {
          acc.push(project);
        }

        return acc;
        }, []);
      }
    
    return processedProjects.sort(sortProjects);
```

2024-04-29 14:00 UTC, arthurgeron approved these changes

2024-04-29 14:21 UTC, helciofranco commented on packages/app-portal/src/systems/Ecosystem/hooks/useEcosystem.tsx
> +    return projects.sort(sortProjects);
indeed, great suggestion, let's check later if we need to support filter + search at same time.
currently the state machine is allowing only one or other – so I'm not sure if it was an existing product requirement.

2024-04-29 17:29 UTC, LuizAsFight requested changes
codewise looking good but preview PR link is broken

2024-04-29 19:09 UTC, helciofranco commented
> codewise looking good but preview PR link is broken

@LuizAsFight  I updated our env. vars to use `beta-5` API again, now it's all set.

2024-04-30 09:38 UTC, HoTandy approved these changes
Looks good!

2024-04-30 11:23 UTC, helciofranco commented
@LuizAsFight can you review it again plz?

2024-04-30 12:39 UTC, HoTandy approved these changes
I've done a quick second review and all looks good.

2024-05-27 17:25 UTC, LuizAsFight approved these changes

2024-05-27 17:25 UTC, merged

2024-05-28 08:03 UTC, HoTandy reviewed
Now all DApps 👍