docs: update README with latest setup
FuelLabs/fuel-explorer pull request #322
Opened 2024-04-29 16:19 UTC by helciofranco

- Add missing instructions to run e2e tests.
- Remove duplicated packages between `portal` and `explorer`.
- Add scripts to run `storybooks`.
- Replace `date-fns` with `dayjs` in portal (in order to keep only one date library in the project).

Closes #275

2024-04-29 20:44 UTC, arthurgeron approved these changes

2024-04-30 09:40 UTC, HoTandy commented
@helciofranco I'm getting a `404` when clicking on `View deployment`. Has something gone wrong since you deployed?

2024-04-30 10:50 UTC, helciofranco commented
@HoTandy I've just started a new deploy, there was an issue with the infra setup (not related with my changes)
this should be all set in 10 minutes.

2024-04-30 13:01 UTC, HoTandy approved these changes
I think this is looking better now, less confusion and now referencing the correct .env file

2024-05-27 21:34 UTC, LuizAsFight requested changes

2024-05-27 21:37 UTC, helciofranco commented on package.json
> +    "storybook:ui": "pnpm turbo:run dev:storybook --filter=@fuels/ui",
I think so!

https://github.com/FuelLabs/fuel-explorer/pull/322/commits/a8df239de93b2553f618b64525f6e0280f80b68c

2024-05-27 22:27 UTC, LuizAsFight submitted a review, later dismissed

2024-05-27 23:18 UTC, LuizAsFight approved these changes

2024-05-27 23:18 UTC, merged