feat: add primitives package
FuelLabs/fuel-explorer pull request #38
Opened 2023-09-20 21:42 UTC by pedronauck

2023-09-21 20:13 UTC, luizstacio requested changes

2023-09-21 20:13 UTC, luizstacio commented on packages/ui/src/components/Spinner/Spinner.tsx
> +    );
you can type `Record<string, string>` instead of any.?

2023-09-21 20:13 UTC, luizstacio commented on packages/ui/src/components/Theme/useTheme.tsx
> +export function useTheme(): any {
We should remove any from here.

We should be able to configure the localStorage key. It can be as simple as export a const CONFIG = { themeKey }.

2023-09-21 20:13 UTC, luizstacio commented on packages/ui/src/components/Toast/toaster.tsx
> +            style={{ '--radix-toast-width': `${width}px` } as any}
Why using any everywhere... this component has a CSS this should go there.

2023-09-22 19:18 UTC, pedronauck commented on packages/ui/src/components/Toast/toaster.tsx
> +            style={{ '--radix-toast-width': `${width}px` } as any}
This is not a CSS definition, the only way to set a CSS variable inline for the component getting from the props is like that

2023-09-22 19:23 UTC, pedronauck commented on packages/ui/scripts/add-use-client.mjs
> +main();
removed

2023-09-22 19:24 UTC, pedronauck commented on packages/ui/scripts/create-defs.mjs
> +  // await tsup(components);
It's because this script is very manually/arbitrary, sometimes I'm using some generations, sometimes others

2023-09-22 19:30 UTC, pedronauck commented on packages/ui/src/components/ButtonClose/ButtonClose.tsx
> +  baseElement: IconButton as any,
✅

2023-09-22 19:30 UTC, pedronauck commented on packages/ui/src/components/ButtonGroup/ButtonGroup.stories.tsx
> +      <Button>Third</Button>
✅

2023-09-22 20:06 UTC, pedronauck commented on packages/ui/src/components/Nav/Nav.tsx
> +          >
can you add this as an issue to do later?

2023-09-22 20:06 UTC, pedronauck commented on packages/ui/src/components/RadioGroup/RadioGroup.stories.tsx
> +        </label>
just copied from the Radix theme

2023-09-22 20:06 UTC, pedronauck commented on packages/ui/src/components/Spinner/Spinner.tsx
> +    );
✅

2023-09-22 20:14 UTC, pedronauck commented on packages/ui/src/components/Theme/useTheme.tsx
> +export function useTheme(): any {
✅

2023-09-23 03:49 UTC, closed without merging