feat: update design system colors
FuelLabs/fuel-explorer pull request #386
Opened 2024-06-20 21:21 UTC by arthurgeron

- Added back primary and secondary text color variables
- Updated all colors to match the new Design System colors
- Standardized borders to use `border` color, and set it to be `gray-6`, which is aligned with Radix's color science.

![image](https://github.com/FuelLabs/fuel-explorer/assets/3487334/0b0f3d50-0865-409d-b22c-951816c2d404)
![image](https://github.com/FuelLabs/fuel-explorer/assets/3487334/801bca01-b59f-44de-95e5-a20f3ced1ab5)
![image](https://github.com/FuelLabs/fuel-explorer/assets/3487334/9cb4902a-7697-43b7-8927-5f15ce92bd94)

2024-06-21 15:24 UTC, LuizAsFight requested changes
transaction and block page not accessible, internal server error 500

2024-06-21 15:53 UTC, arthurgeron commented
> transaction and block page not accessible, internal server error 500

Next.JS still executes some client-component code during SSR or SSG, even for client components, and `router.prefetch` called in `ViewMode` accesses `window` internally, which causes the error in prod. 
I've fixed the code to only run client side.

2024-06-24 00:04 UTC, LuizAsFight approved these changes

2024-06-24 00:04 UTC, LuizAsFight approved these changes

2024-06-24 00:15 UTC, merged