fix: list coin outputs properly
FuelLabs/fuel-explorer pull request #433
Opened 2024-07-25 20:56 UTC by helciofranco

Closes https://github.com/FuelLabs/fuel-explorer/issues/431

---

We've been listing only one `CoinOutput` per transaction, however, there are more than only one `CoinOutput` in transfer operations between wallets (e.g. from our faucet).

| 📷 Outputs |
| --- |
| <img width="772" alt="Screenshot 2024-07-25 at 16 54 30" src="https://github.com/user-attachments/assets/2c5e2504-cd4e-45ce-aa8a-8a072e85735a"> |

| 📷 UI |
| --- |
| <img width="1172" alt="Screenshot 2024-07-25 at 16 55 02" src="https://github.com/user-attachments/assets/4d283e1f-f2eb-4cb7-84d1-c5eef2552904"> |

2024-07-27 02:45 UTC, LuizAsFight requested changes
the change output should also be receiving?

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/22a33796-7ef1-4135-a2a8-468f0b79ecdf">

2024-07-29 21:05 UTC, helciofranco commented
@LuizAsFight 

<img width="645" alt="Screenshot 2024-07-29 at 17 04 45" src="https://github.com/user-attachments/assets/c7583796-0cef-40aa-b7da-8a242086008c">

2024-07-30 00:10 UTC, arthurgeron approved these changes

2024-07-30 19:36 UTC, arthurgeron approved these changes
LGTM

2024-08-03 17:54 UTC, LuizAsFight approved these changes

2024-08-03 17:54 UTC, merged