feat: add TxScript component
FuelLabs/fuel-explorer pull request #64
Opened 2023-10-18 03:08 UTC by pedronauck

2023-10-18 19:01 UTC, luizstacio requested changes

2023-10-18 19:01 UTC, luizstacio commented on packages/graphql/src/services/extender/index.ts
> +  JSONObject: GraphQLJSONObject,
I think we don't need this part here, and just use the receipts, if we want to use the operations from the ts-SDK, we should return inside the transaction itself, typing it. We can probably to the type from the ts-sdk also, and just convert from typescript to graphql

2023-10-18 19:04 UTC, luizstacio commented
I think the transaction type is not looking good, maybe we could add as a new line, and use the icon, we have on the card... or just a new line. But the two columns look weird.

2023-10-20 14:19 UTC, luizstacio commented on packages/graphql/src/services/extender/extender.graphql
> +scalar JSONObject
We can remove this scalars now correct?

2023-10-23 20:23 UTC, pedronauck commented on packages/graphql/src/services/extender/extender.graphql
> +scalar JSONObject
✅

2023-10-23 20:35 UTC, luizstacio approved these changes

2023-10-23 20:35 UTC, merged