Pn/feat/acc page
FuelLabs/fuel-explorer pull request #76
Opened 2023-10-24 02:06 UTC by pedronauck

⭐ Closes [FRO-654](https://linear.app/fuel-network/issue/FRO-654/account-page-assets) [FRO-662](https://linear.app/fuel-network/issue/FRO-662/account-page)

2023-10-24 03:40 UTC, luizstacio requested changes
- I think we should add a min-height on the screen.
- The URL should also accept bech32 accounts `fuel18e7amfxs60urq7h97xhdsa3rnykpcn0valkxsjfkjcrh2xqmyvpq4ay9jn`

2023-10-24 04:52 UTC, LuizAsFight submitted a review, later dismissed

2023-10-24 20:18 UTC, LuizAsFight submitted a review, later dismissed

2023-10-25 02:40 UTC, luizstacio commented
Now if the button on the UTXO the screen is broken on the Tx Page.
<img width="848" alt="Screenshot 2023-10-24 at 11 39 49 PM" src="https://github.com/FuelLabs/fuel-explorer/assets/3941923/723fb9df-1805-4e03-8086-82f0c5b2e017">

2023-10-25 19:07 UTC, pedronauck commented
changes addressed @luizstacio ✅

2023-10-25 19:38 UTC, luizstacio approved these changes

2023-10-25 19:39 UTC, merged