chore: improve graphql dev command
FuelLabs/fuel-explorer pull request #85
Opened 2023-10-27 23:53 UTC by pedronauck

Now after this pull request, in order to have codegen working smoothly just need to run `pnpm dev` inside `packages/graphql` folder, before it was very complicated to get codegen working properly after change any stuff inside the graphql package

2023-10-27 23:55 UTC, luizstacio requested changes

2023-10-27 23:55 UTC, luizstacio commented on packages/graphql/src/bin.ts
> +app.listen(4444);
Why remove the log here?

2023-10-27 23:55 UTC, luizstacio commented on packages/graphql/tsup.config.mjs
> +  clean: false,
Why not clean the files?

2023-10-28 00:19 UTC, pedronauck commented on packages/graphql/tsup.config.mjs
> +  clean: false,
because this was generating errors in the watch mode

2023-10-28 00:22 UTC, pedronauck commented on packages/graphql/src/bin.ts
> +app.listen(4444);
because I changed it to show just after the codegen

2023-10-28 00:47 UTC, LuizAsFight approved these changes

2023-10-28 01:43 UTC, luizstacio approved these changes

2023-10-28 03:14 UTC, merged