feat: add predicate section for accounts
FuelLabs/fuel-explorer pull request #95
Opened 2023-11-01 22:24 UTC by pedronauck

2023-11-02 14:49 UTC, luizstacio requested changes
- Again consider doing less changes on the overall application when doing features, it makes difficult to review the PR with orthogonal changes.

2023-11-02 14:49 UTC, luizstacio commented on packages/app/src/app/account/[id]/transactions/page.tsx
> +export const revalidate = 1;
Let's keep 10 seconds

2023-11-02 14:49 UTC, luizstacio commented on packages/app/src/app/transactions/[page]/page.tsx
> +export const revalidate = 1;
We can keep 10 seconds here. Also it's possible to add conditional logic here? If the status of the transaction is success or failure the transaction will not change anymore and don't need to be revalidated

2023-11-02 14:49 UTC, luizstacio commented on packages/app/src/systems/Account/actions/get-predicate-bytecode.ts
> +});
This logic should be on the Graphql endpoint, we could create a resolver on the graphql `predicate(address: string)` that does the magic of checking and return the data needed on the UI

2023-11-03 20:33 UTC, pedronauck commented on packages/app/src/app/account/[id]/transactions/page.tsx
> +export const revalidate = 1;
✅

2023-11-03 20:34 UTC, pedronauck commented on packages/app/src/app/transactions/[page]/page.tsx
> +export const revalidate = 1;
✅

2023-11-03 20:34 UTC, pedronauck commented on packages/app/src/systems/Account/actions/get-predicate-bytecode.ts
> +});
✅

2023-11-03 21:00 UTC, luizstacio requested changes
- (This tx)[https://fuel-explorer-11lxmw70s-fuel-labs.vercel.app/tx/0x96e4020a05d97d69f99d0e08008c9b5318ed5edff315065fe5e405b94bb2bc1d] It's showing a predicate tag on a contractCall but the transaction not contains a predicate.
- On predicate endpoint in the graphql we should only return predicate as predicateData can be different for each transaction.

2023-11-06 23:30 UTC, luizstacio approved these changes

2023-11-06 23:30 UTC, merged