feat: block page simple
FuelLabs/fuel-explorer pull request #96
Opened 2023-11-02 19:41 UTC by matt-user

closes #91

2023-11-03 22:16 UTC, pedronauck submitted a review, later dismissed

2023-11-03 22:27 UTC, pedronauck requested changes
Can you link the `blockHeight` in the transaction? There's any place with link for blocks pages I guess

2023-11-06 13:03 UTC, luizstacio commented
> Can you link the `blockHeight` in the transaction? There's any place with link for blocks pages I guess

We can do this in another task also

2023-11-06 14:49 UTC, matt-user commented
> > Can you link the `blockHeight` in the transaction? There's any place with link for blocks pages I guess
> 
> We can do this in another task also

I created a separate issue https://linear.app/fuel-network/issue/FE-9/link-to-block-page

2023-11-06 16:41 UTC, pedronauck approved these changes

2023-11-06 16:41 UTC, merged